### ISSUE TITLE
General Product  check (prod / bokun) issues

### ISSUE THREAD

**Issue by justas79** [Bokun/grayline_ar_inventory_plugin#16]
Ex. product: Golden Circle Super Jeep Tour, Reykjavik. 
https://grayline.is/tours/reykjavik/golden-circle-super-jeep-tour-with-snowmobile-8706_11/
id on test API: 900

- API return pickup available ~70 hotels, but product description shows pickup unavailable. 

- Availability is shown as unavailable, unless you specify start time of 9:00 (which is not correct)

- When 9:00 set, returns all days as available, even some on prod are not

**Comment by vidasmiliauskas** [comment]
1st item fixed. Other two explained as correct behavior
