### ISSUE TITLE
Airport and zone description not taken into account

### ISSUE THREAD

**Issue by justas79** [Bokun/grayline_ar_inventory_plugin#6]
Pickups from aiport (airpot / zone_description) are not taken into account

**Comment by vidasmiliauskas** [comment]
The example Blue Lagoon has no Airport pickup place when booked from GL Argentina (you are referring to GL Iceland). Airport pickup has not been detected in API data for tours. Anyway, airport can be configured as pickup location on Bokun side and then it will be passed to API as string (which is also allowed option).
