### ISSUE TITLE
Price per person parsing

### ISSUE THREAD

**Issue by justas79** [Bokun/grayline_ar_inventory_plugin#7]
I guess this:

    public static boolean isPricePerPerson(Season season) {
        return !season.priceType.equals("Unico");
    }

will fail to return correct value for ex.: "Price_adult" (price per vehicle) ??

**Comment by vidasmiliauskas** [comment]
This helper method only identifies pricing type: per person or per booking.
Then other code, after calling this method, should act accordingly, without fail.
